# Generated by Django 2.2.3 on 2020-10-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('d_information_management_app', '0001_initial'),
        ('a_students_app', '0002_auto_20201028_1249'),
        ('b_activities_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchstays',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Institution'),
        ),
        migrations.AddField(
            model_name='publication',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='b_activities_app.Activity'),
        ),
        migrations.AddField(
            model_name='projectcourse',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='b_activities_app.Activity'),
        ),
        migrations.AddField(
            model_name='projectcourse',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_students_app.Program'),
        ),
        migrations.AddField(
            model_name='prize',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='b_activities_app.Activity'),
        ),
        migrations.AddField(
            model_name='presentationresults',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='b_activities_app.Activity'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='b_activities_app.Activity'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Institution'),
        ),
        migrations.AddField(
            model_name='participationprojects',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='b_activities_app.Activity'),
        ),
        migrations.AddField(
            model_name='participationprojects',
            name='investigation_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.InvestigationLine'),
        ),
        migrations.AddField(
            model_name='participationprojects',
            name='investigator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Professor'),
        ),
        migrations.AddField(
            model_name='activity',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_students_app.Student'),
        ),
    ]
