# Generated by Django 2.2.3 on 2020-10-29 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('d_information_management_app', '0001_initial'),
        ('b_activities_app', '0001_initial'),
        ('a_students_app', '0002_auto_20201029_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchstays',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.City'),
        ),
        migrations.AddField(
            model_name='researchstays',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Country'),
        ),
        migrations.AddField(
            model_name='researchstays',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Institution'),
        ),
        migrations.AddField(
            model_name='projectcourse',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_students_app.Program'),
        ),
        migrations.AddField(
            model_name='participationprojects',
            name='investigation_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.InvestigationLine'),
        ),
        migrations.AddField(
            model_name='participationprojects',
            name='investigator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Professor'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Institution'),
        ),
    ]
