# Generated by Django 2.2.3 on 2020-10-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_code',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_id',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(upload_to='d_accounts_app/users'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['personal_id', 'personal_code'], name='d_accounts__persona_84b149_idx'),
        ),
    ]
