# Generated by Django 2.2.3 on 2020-10-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_students_app', '0002_auto_20201029_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrrollment',
            name='state',
            field=models.IntegerField(choices=[(1, 'ACTIVO'), (2, 'INACTIVO'), (3, 'GRADUADO'), (4, 'BALANCEADO'), (5, 'RETIRADO')]),
        ),
    ]
