# Generated by Django 2.2.3 on 2020-10-31 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_information_management_app', '0002_academictraining'),
        ('a_students_app', '0003_auto_20201030_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.IntegerField(choices=[(1, 'DIRECTOR'), (2, 'COODIRECTOR')], default=1, verbose_name='rol')),
                ('date_record', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Professor', verbose_name='profesor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_students_app.Student', verbose_name='estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroupInvestigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_start_date', models.DateField()),
                ('membership_end_date', models.DateField()),
                ('date_record', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('line_investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Professor', verbose_name='linea de investigacion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_students_app.Student', verbose_name='estudiante')),
            ],
        ),
    ]
