# Generated by Django 2.2.3 on 2020-10-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('d_information_management_app', '0001_initial'),
        ('a_projects_app', '0001_initial'),
        ('a_students_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='investigation_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.InvestigationLine'),
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_students_app.Student'),
        ),
        migrations.AddField(
            model_name='objetive',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_projects_app.Project'),
        ),
        migrations.AddField(
            model_name='general',
            name='objetive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_projects_app.Objetive'),
        ),
        migrations.AddField(
            model_name='directorcontrol',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Professor'),
        ),
        migrations.AddField(
            model_name='directorcontrol',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_projects_app.Project'),
        ),
        migrations.AddField(
            model_name='codirectorcontrol',
            name='codirector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Professor'),
        ),
        migrations.AddField(
            model_name='codirectorcontrol',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_projects_app.Project'),
        ),
    ]
