# Generated by Django 2.2.3 on 2020-10-29 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_students_app', '0001_initial'),
        ('b_activities_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCoordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(default=0)),
                ('observations', models.CharField(max_length=148)),
                ('date_record', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Evaluación del coordinador',
                'verbose_name_plural': 'Evaluaciónes de los coordinadores',
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'ACTIVO'), (2, 'INACTIVO'), (3, 'GRADUADO'), (4, 'BALANCEADO'), (5, 'RETIRADO')], default=1)),
                ('enrollment_date', models.DateField()),
                ('graduation_date', models.DateField()),
                ('num_folio', models.CharField(max_length=24)),
                ('num_acta', models.CharField(max_length=24)),
                ('num_diploma', models.CharField(max_length=24)),
                ('num_resolution', models.CharField(max_length=24)),
                ('observations', models.CharField(blank=True, max_length=148)),
                ('date_record', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_students_app.Student')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
            },
        ),
        migrations.CreateModel(
            name='TestDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(default=0)),
                ('observations', models.CharField(max_length=148)),
                ('date_record', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b_activities_app.Activity')),
            ],
            options={
                'verbose_name': 'Evaluación del director',
                'verbose_name_plural': 'Evaluaciónes de los directores',
            },
        ),
    ]
