# Generated by Django 2.2.3 on 2020-10-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('d_information_management_app', '0001_initial'),
        ('b_activities_app', '0002_auto_20201028_1249'),
        ('c_tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdirector',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Professor'),
        ),
        migrations.AddField(
            model_name='testcoordinator',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b_activities_app.Activity'),
        ),
        migrations.AddField(
            model_name='testcoordinator',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Professor'),
        ),
    ]
