# Generated by Django 2.2.3 on 2020-10-30 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b_activities_app', '0002_auto_20201029_1108'),
        ('d_information_management_app', '0002_academictraining'),
        ('c_tracking_app', '0003_auto_20201029_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.IntegerField(choices=[(1, 'DIRECTOR'), (2, 'COODIRECTOR')], default=1)),
                ('date_record', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_activities_app.Activity')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Professor')),
            ],
            options={
                'verbose_name': 'Actividad de un profesor',
                'verbose_name_plural': 'Actividades de un profesor',
            },
        ),
    ]
