# Generated by Django 2.2.3 on 2020-10-31 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_tracking_app', '0004_activityprofessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityprofessor',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_activities_app.Activity', verbose_name='actividad'),
        ),
        migrations.AlterField(
            model_name='activityprofessor',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Professor', verbose_name='profesor'),
        ),
        migrations.AlterField(
            model_name='activityprofessor',
            name='rol',
            field=models.IntegerField(choices=[(1, 'DIRECTOR'), (2, 'COODIRECTOR'), (2, 'COORDINADOR')], default=1, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='testcoordinator',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b_activities_app.Activity', verbose_name='actividad'),
        ),
        migrations.AlterField(
            model_name='testcoordinator',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Professor', verbose_name='profesor'),
        ),
        migrations.AlterField(
            model_name='testcoordinator',
            name='credits',
            field=models.IntegerField(default=0, verbose_name='creditos'),
        ),
        migrations.AlterField(
            model_name='testcoordinator',
            name='observations',
            field=models.CharField(max_length=148, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='testdirector',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b_activities_app.Activity', verbose_name='actividad'),
        ),
        migrations.AlterField(
            model_name='testdirector',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Professor', verbose_name='profesor'),
        ),
        migrations.AlterField(
            model_name='testdirector',
            name='observations',
            field=models.CharField(max_length=148, verbose_name='observacion'),
        ),
        migrations.AlterField(
            model_name='testdirector',
            name='value',
            field=models.IntegerField(choices=[(1, 'FAVORABLE'), (2, 'NO_FAVORABLE')], default=1, verbose_name='calificacion'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='enrollment_date',
            field=models.DateField(verbose_name='fecha de matricula'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='graduation_date',
            field=models.DateField(verbose_name='fecha de graduación'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='num_acta',
            field=models.CharField(max_length=24, verbose_name='numero de acta'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='num_diploma',
            field=models.CharField(max_length=24, verbose_name='numero de diploma'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='num_folio',
            field=models.CharField(max_length=24, verbose_name='numero de folio'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='num_resolution',
            field=models.CharField(max_length=24, verbose_name='numero de resolucion'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='observations',
            field=models.CharField(blank=True, max_length=148, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='state',
            field=models.IntegerField(choices=[(1, 'ACTIVO'), (2, 'INACTIVO'), (3, 'GRADUADO'), (4, 'BALANCEADO'), (5, 'RETIRADO')], default=1, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_students_app.Student', verbose_name='estudiante'),
        ),
    ]
